### PR TITLE
upgraded to micronaut 4 and resolve security vuls

### PR DESCRIPTION
**Pull request by munishchouhan**
This PR will do the following:
1. upgrade to mn 4
2. upgrade pther deps to solve security vuls

### CODE REVIEW

**Review by jordeu — COMMENTED** [review]
Getting an error when giving it a try:
```
$ java -jar tw-agent.jar -V
19:12:27.923 INFO - Established active environments: [cli]
java.lang.NullPointerException: inStream parameter is null
	at java.base/java.util.Objects.requireNonNull(Objects.java:259)
	at java.base/java.util.Properties.load(Properties.java:408)
	at io.seqera.tower.agent.utils.VersionProvider.getVersion(VersionProvider.java:29)
	at picocli.CommandLine$Model$CommandSpec.version(CommandLine.java:7201)
	at picocli.CommandLine.printVersionHelp(CommandLine.java:2858)
	at picocli.CommandLine.executeHelpRequest(CommandLine.java:2001)
	at picocli.CommandLine.executeHelpRequest(CommandLine.java:1987)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2272)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at io.micronaut.configuration.picocli.PicocliRunner.run(PicocliRunner.java:146)
	at io.micronaut.configuration.picocli.PicocliRunner.run(PicocliRunner.java:123)
	at io.seqera.tower.agent.Agent.main(Agent.java:103)
```

**Comment by munishchouhan** [comment]
I got this:
```
(base) Munishs-MacBook-Pro:libs munish.chouhan$  java -jar tw-agent.jar -V
10:12:37.900 INFO - Established active environments: [cli]
Tower Agent version 0.5.0 (build unknown)
```

**Comment by munishchouhan** [comment]
Tested native-image:
```
nativeCompile % ./tw-agent --version
10:05:00.479 INFO - Established active environments: [cli]
Tower Agent version 0.5.0 (build unknown)
(base) munish.chouhan@Munishs-MacBook-Pro nativeCompile % ./tw-agent --help
10:05:19.132 INFO - Established active environments: [cli]

Usage: tw-agent [OPTIONS] AGENT_CONNECTION_ID

Nextflow Tower Agent

Parameters:
*     AGENT_CONNECTION_ID    Agent connection ID to identify this agent.

Options:
* -t, --access-token=<token> Tower personal access token. If not provided TOWER_ACCESS_TOKEN variable will be used.
  -u, --url=<url>            Tower server API endpoint URL. If not provided TOWER_API_ENDPOINT variable will be used [default: https://api.tower.nf].
  -w, --work-dir=<workDir>   Default path where the pipeline scratch data is stored. It can be changed when launching a pipeline from Tower [default: ~/work].
  -h, --help                 Show this help message and exit.
  -V, --version              Print version information and exit.
```

**Comment by jordeu** [comment]
@munishchouhan from where do you get the JAR file and binaries? Are you using the generated artifact versions? here: https://github.com/seqeralabs/tower-agent/actions/runs/12280294497

**Comment by munishchouhan** [comment]
Thanks for clarifying it
I was testing the jar built locally 
There may be a issue with java version
I will check further

**Comment by munishchouhan** [comment]
@jordeu fixed now
```
Downloads % java -jar tw-agent.jar -V --debug
18:55:27.607 INFO - Established active environments: [cli]
Tower Agent version 0.5.0 (build 90bde02)
```

**Review by jordeu — APPROVED** [review]
Thanks @munishchouhan !

**Pull request merged**
