### PR TITLE
Expand payload to 10MB

### PR DESCRIPTION
**Pull request by mbosio85**
expands the maximum payload to 10MB

### CODE REVIEW

**Comment by pditommaso** [comment]
We may have found who is collapsing Platform memory ..

**Comment by mbosio85** [comment]
I forgot to mention that this is related to partially solve the issue mentioned in:
https://seqera.atlassian.net/browse/PLAT-280 "[Bug] Seqera Platform displays truncated reports when using Tower Agent"

**Comment by mbosio85** [comment]
@pditommaso , 
>We may have found who is collapsing Platform memory ..

Is this an actual worry? If so, 2x or 3x the max payload may create additional pressure.
I would wait to merge this until we are sure it's safe.
Also, I'd increase it to 15MB to match the value on the platform side and to answer @ewels's request in https://seqera.atlassian.net/browse/PLAT-280

**Comment by jordeu** [comment]
It should theoretically be possible to leverage Websocket fragmentation (I don't know how to use it from Micronaut), but it may make things more difficult because there are other messages like "command-request", "heartbeat," and "info" that we may need to "defragment" and handle on our side the JSON deserialization. So, adding a new message, "command-response-fragment", may make things easier with the current setup and more backwards compatible. On top of this, we need to stream the fragments throw Redis so we may end up fragmenting again the websocket fragments.

Regarding "there's a suspect that the agent is related to the abnormal usage of memory in the platform", I suspect that the use of `countSubscribers` in Redis is not always working properly, so it might be related.

Overall, a more long-term solution to decouple this complexity could be to leverage Seqera Connect to handle the Agent-Platform communication channel.

**Comment by mbosio85** [comment]
>Overall, a more long-term solution to decouple this complexity could be to leverage Seqera Connect to handle the Agent-Platform communication channel.

While we wait/decide on a longer-term solution, I'd move this PR forward knowing it is a stop-gap.

**Comment by robnewman** [comment]
@jordeu Any progress on this PR review?

**Comment by pditommaso** [comment]
Think it's fine to move ahead, but we need to plan a more sustainable solution

**Review by jordeu — APPROVED** [review]
Take into account that this 10485760 size will allow to transfer files of ~7.5MB because they are base64 encoded. We cannot increase much more without changing also the limit that we have on platform side. 

Agent was never thought to transfer files, only to execute commands. In fact, we are transferring files using a command line execution of a `cat`. This is very inefficient and we should plan to add proper support for transferring files.

**Comment by robnewman** [comment]
@jordeu Thanks for the review. The build is failing the checks. Anything we can do about that?

**Comment by jordeu** [comment]
Seems that GH Actions are broken and need an update. I can check tomorrow.

**Comment by robnewman** [comment]
@jordeu Any chance we could get this fixed on Monday so we can provide an update to the customer? Thanks!

**Comment by jordeu** [comment]
After merging https://github.com/seqeralabs/tower-agent/pull/54 we'll be able to update and build this branch.

**Comment by jordeu** [comment]
Meanwhile, we wait for #54 approval, I've rebased this PR on top of that so it builds the binary and JAR distributions that can be downloaded from the artifacts section here: https://github.com/seqeralabs/tower-agent/actions/runs/10998755756

@robnewman @mbosio85 if you wish you can download and test it from there.

**Pull request merged**
